version: '3'

networks:
  server:
    driver: bridge
# docker-compose up --build
services:
  reverse-proxy-container:
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    environment:
      TZ: Asia/Seoul
    depends_on:
      django:
        condition: service_healthy
    networks:
      - server

  # 컨테이너 빌드
  # docker run --name fastapi -d -p 8000:8800(호스트:컨테이너) fastapiapp
  django:
    build:
      context: .
      dockerfile : Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 300s
      timeout: 3s
      retries: 1
    networks:
      - server

